# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cc6b0446c79eb6cae330402f0a15be6b6fc46291b3432866e985422fb1c3246abd67951231076da5afdef29e8603d97e5139cb973203aa6b9ac5bc386a7cfdd

test:
  secret_key_base: 110781d964b772044c1cd6388b39c2fb92eec760482027a00ef79c6d44e3ce987d43c3af8a864b9f96428abc7b4d8c380a2569dd0e342780294597cd77f9beca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
